//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SARH.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CATADirecionesArea
    {
        public int idDireccionArea { get; set; }
        public string DA_Nombre { get; set; }
        public string DA_Iniciales { get; set; }
        public int idCATAAreasFuncional { get; set; }
        public byte Estatus { get; set; }
        public System.DateTime FechaAlta { get; set; }
        public System.DateTime FechaBaja { get; set; }
    }
}
