//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SARH.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CATANivelEstudios
    {
        public short idCATANivelEstudios { get; set; }
        public string Nivel { get; set; }
        public byte ControlRegistroHistorial { get; set; }
        public byte Orden { get; set; }
        public byte ExigeFechaFin { get; set; }
    }
}
