//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SARH.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CATACodigosPlaza
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CATACodigosPlaza()
        {
            this.Plazas = new HashSet<Plazas>();
        }
    
        public short idCATACodigosPlaza { get; set; }
        public string descripcion { get; set; }
        public string NivelPlaza { get; set; }
        public decimal SueldoBase { get; set; }
        public decimal Compensacion { get; set; }
        public string idFiltroPuestoClave { get; set; }
        public Nullable<decimal> SueldoBruto { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Plazas> Plazas { get; set; }
    }
}
