//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SARH.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CATANivelPuesto
    {
        public byte idCATANivelPuesto { get; set; }
        public string DescripcionNivelPuesto { get; set; }
        public byte idCATACategoria { get; set; }
    
        public virtual CATACategoria CATACategoria { get; set; }
    }
}
