//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SARH.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CATACategoria
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CATACategoria()
        {
            this.CATANivelPuesto = new HashSet<CATANivelPuesto>();
        }
    
        public byte idCATACategoria { get; set; }
        public string DescripcionCategoria { get; set; }
        public byte idCATATipoPlazaNuevo { get; set; }
    
        public virtual CATATipoPlazaNuevo CATATipoPlazaNuevo { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CATANivelPuesto> CATANivelPuesto { get; set; }
    }
}
