//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SARH.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Correos
    {
        public int idCorreo { get; set; }
        public int idPersonal { get; set; }
        public byte idCATATipoCorreo { get; set; }
        public string Correo { get; set; }
        public byte idCATAEstatus { get; set; }
        public System.DateTime FechaRegistro { get; set; }
        public Nullable<System.DateTime> FechaBaja { get; set; }
    
        public virtual CATAEstatus CATAEstatus { get; set; }
        public virtual CATATipoCorreo CATATipoCorreo { get; set; }
    }
}
