//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SARH.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class HistorialAltasBajasPersonas
    {
        public int idHistorialAltasBajasPersonas { get; set; }
        public int idPersonal { get; set; }
        public System.DateTime FechaAlta { get; set; }
        public System.DateTime FechaBaja { get; set; }
        public byte idCATAEstatusRegistro { get; set; }
        public byte idCATAMotivoBaja { get; set; }
    
        public virtual CATAMotivoBaja CATAMotivoBaja { get; set; }
    }
}
