//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SARH.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class HistorialPerPlazas
    {
        public int idHistorialPerPlazas { get; set; }
        public int idPersonal { get; set; }
        public int idPlazas { get; set; }
        public System.DateTime fechaAsignacionPlaza { get; set; }
        public short idCATAAreasFuncionales { get; set; }
        public short idTipoMovimiento { get; set; }
        public string CargoFuncional { get; set; }
        public string Funciones { get; set; }
        public System.DateTime fechaRegistro { get; set; }
        public int estatusHistorialPerPlazasActual { get; set; }
        public Nullable<System.DateTime> FechaDesasignacion { get; set; }
        public Nullable<int> idDireccionArea { get; set; }
    }
}
