//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SARH.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Personal
    {
        public int idPersonal { get; set; }
        public string apellidoPaterno { get; set; }
        public string ApellidoMaterno { get; set; }
        public string nombres { get; set; }
        public string nombreCompleto { get; set; }
        public System.DateTime fechaNacimiento { get; set; }
        public string RFC { get; set; }
        public string Homoclave { get; set; }
        public string CURP { get; set; }
        public string Sexo { get; set; }
        public System.DateTime fechaIngresoInstitucion { get; set; }
        public byte idCATAEstatus { get; set; }
        public byte[] Fotografia { get; set; }
        public Nullable<System.DateTime> fechaRegistro { get; set; }
        public Nullable<byte> idCATAParents { get; set; }
    }
}
