//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SARH.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Plazas
    {
        public int idPlazas { get; set; }
        public string numeroPlaza { get; set; }
        public short idCATAPuestos { get; set; }
        public short idCATACodigosPlaza { get; set; }
        public string CargoEstructura { get; set; }
        public string ClavePresupuestal { get; set; }
        public byte idCATAEstatusPlaza { get; set; }
        public System.DateTime fechaRegistro { get; set; }
    
        public virtual CATACodigosPlaza CATACodigosPlaza { get; set; }
        public virtual CATAEstatusPlaza CATAEstatusPlaza { get; set; }
        public virtual CATAPuestos CATAPuestos { get; set; }
    }
}
