//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SARH.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_DetallePersonal
    {
        public string Nombre_Completo { get; set; }
        public System.DateTime Fecha_de_Nacimiento { get; set; }
        public string RFC { get; set; }
        public string Homoclave { get; set; }
        public string CURP { get; set; }
        public string Sexo { get; set; }
        public System.DateTime Fecha_Ingreso_Institución { get; set; }
        public Nullable<System.DateTime> Fecha_Registro { get; set; }
        public string Descripcion { get; set; }
    }
}
