//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SARH.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_PlazasVacantes
    {
        public string numeroPlaza { get; set; }
        public short idCATAPuestos { get; set; }
        public string NombrePuesto { get; set; }
        public short idCATACodigosPlaza { get; set; }
        public string descripcion { get; set; }
        public string NivelPlaza { get; set; }
        public decimal SueldoBase { get; set; }
        public decimal Compensacion { get; set; }
        public Nullable<decimal> SueldoBruto { get; set; }
        public string CargoEstructura { get; set; }
        public string ClavePresupuestal { get; set; }
        public byte idCATAEstatusPlaza { get; set; }
        public string Estatus { get; set; }
        public System.DateTime fechaRegistro { get; set; }
    }
}
